/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include <mylibrary.h>
#include "app.h"

std::string greeting() {
    return std::string("Hello, World!");
}

int main () {
    std::cout << greeting() << std::endl;
    std::cout << getHello() << std::endl;

    return 0;
}
